apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-sywa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-sywa
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-sywa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-sywa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-sywa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-syfo-tenant/rhtap-demo-app/hacbs-test-project-sywa@sha256:1afd2de3761683622811cb7ddb8e8425bfc3c53a331b6c946a51c534469ea497
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
