apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sywa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-syfo-tenant/rhtap-demo-app/hacbs-test-project-sywa@sha256:f092d66c45ff081b390628fca85f60edae126df0c1fea0091d1129010f33cd71
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
