apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sywa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-syfo-tenant/rhtap-demo-app/hacbs-test-project-sywa@sha256:1afd2de3761683622811cb7ddb8e8425bfc3c53a331b6c946a51c534469ea497
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
